version: '3'

services:
  db_postgres_ng_cash:
    image: postgres
    container_name: db_postgres_ng_cash
    restart: always
    ports:
      - 5005:5432
    env_file:
      - .env
    volumes:
      - pg_ng_cash:/var/lib/postgresql/data

  node_app_ng_cash:
    container_name: node_ng_cash
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_ng_cash
    env_file:
      - .env

volumes:
  pg_ng_cash:
